// Code generated by protoc-gen-go.
// source: loginsvr.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	loginsvr.proto

It has these top-level messages:
	MRegisterServerReq
	MSavePlayerDataReq
	MUserInternalVerifyReq
	MUpdatePlayerRankReq
	MCheckCanBuyOlshopItemReq
	MCheckCanBuyOlshopItemRsp
	MSavePlayerExtDataReq
	MLSAccessNtf
	MVerifyAccountReq
	MQuickMessageNtf
	MServerListItem
	MServerListNtf
	MVerifyAccountRsp
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LSOp int32

const (
	// 	S<->S
	LSOp_RegisterServerReq        LSOp = 11000
	LSOp_SavePlayerDataReq        LSOp = 11001
	LSOp_UserInternalVerifyReq    LSOp = 11002
	LSOp_UpdatePlayerRankReq      LSOp = 11003
	LSOp_CheckCanBuyOlshopItemReq LSOp = 11004
	LSOp_CheckCanBuyOlshopItemRsp LSOp = 11005
	LSOp_SavePlayerExtDataReq     LSOp = 11006
	// 	C<->S
	LSOp_LSAccessNtf      LSOp = 11100
	LSOp_VerifyAccountReq LSOp = 11101
	LSOp_QuickMessageNtf  LSOp = 11102
	LSOp_ServerListNtf    LSOp = 11103
	LSOp_VerifyAccountRsp LSOp = 11104
)

var LSOp_name = map[int32]string{
	11000: "RegisterServerReq",
	11001: "SavePlayerDataReq",
	11002: "UserInternalVerifyReq",
	11003: "UpdatePlayerRankReq",
	11004: "CheckCanBuyOlshopItemReq",
	11005: "CheckCanBuyOlshopItemRsp",
	11006: "SavePlayerExtDataReq",
	11100: "LSAccessNtf",
	11101: "VerifyAccountReq",
	11102: "QuickMessageNtf",
	11103: "ServerListNtf",
	11104: "VerifyAccountRsp",
}
var LSOp_value = map[string]int32{
	"RegisterServerReq":        11000,
	"SavePlayerDataReq":        11001,
	"UserInternalVerifyReq":    11002,
	"UpdatePlayerRankReq":      11003,
	"CheckCanBuyOlshopItemReq": 11004,
	"CheckCanBuyOlshopItemRsp": 11005,
	"SavePlayerExtDataReq":     11006,
	"LSAccessNtf":              11100,
	"VerifyAccountReq":         11101,
	"QuickMessageNtf":          11102,
	"ServerListNtf":            11103,
	"VerifyAccountRsp":         11104,
}

func (x LSOp) Enum() *LSOp {
	p := new(LSOp)
	*p = x
	return p
}
func (x LSOp) String() string {
	return proto.EnumName(LSOp_name, int32(x))
}
func (x *LSOp) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LSOp_value, data, "LSOp")
	if err != nil {
		return err
	}
	*x = LSOp(value)
	return nil
}
func (LSOp) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MRegisterServerReq struct {
	ServerName       *string `protobuf:"bytes,1,req,name=ServerName" json:"ServerName,omitempty"`
	ExposeAddress    *string `protobuf:"bytes,2,req,name=exposeAddress" json:"exposeAddress,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MRegisterServerReq) Reset()                    { *m = MRegisterServerReq{} }
func (m *MRegisterServerReq) String() string            { return proto.CompactTextString(m) }
func (*MRegisterServerReq) ProtoMessage()               {}
func (*MRegisterServerReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MRegisterServerReq) GetServerName() string {
	if m != nil && m.ServerName != nil {
		return *m.ServerName
	}
	return ""
}

func (m *MRegisterServerReq) GetExposeAddress() string {
	if m != nil && m.ExposeAddress != nil {
		return *m.ExposeAddress
	}
	return ""
}

type MSavePlayerDataReq struct {
	LID              *int32  `protobuf:"varint,1,req,name=LID" json:"LID,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	UID              *uint32 `protobuf:"varint,3,req,name=UID" json:"UID,omitempty"`
	Level            *uint32 `protobuf:"varint,4,req,name=Level" json:"Level,omitempty"`
	Data             []byte  `protobuf:"bytes,5,req,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MSavePlayerDataReq) Reset()                    { *m = MSavePlayerDataReq{} }
func (m *MSavePlayerDataReq) String() string            { return proto.CompactTextString(m) }
func (*MSavePlayerDataReq) ProtoMessage()               {}
func (*MSavePlayerDataReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MSavePlayerDataReq) GetLID() int32 {
	if m != nil && m.LID != nil {
		return *m.LID
	}
	return 0
}

func (m *MSavePlayerDataReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MSavePlayerDataReq) GetUID() uint32 {
	if m != nil && m.UID != nil {
		return *m.UID
	}
	return 0
}

func (m *MSavePlayerDataReq) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *MSavePlayerDataReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MUserInternalVerifyReq struct {
	LID              *int32  `protobuf:"varint,1,req,name=LID" json:"LID,omitempty"`
	AccessToken      *string `protobuf:"bytes,2,req,name=AccessToken" json:"AccessToken,omitempty"`
	GID              *int32  `protobuf:"varint,3,req,name=GID" json:"GID,omitempty"`
	ConnCode         *int32  `protobuf:"varint,4,req,name=ConnCode" json:"ConnCode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MUserInternalVerifyReq) Reset()                    { *m = MUserInternalVerifyReq{} }
func (m *MUserInternalVerifyReq) String() string            { return proto.CompactTextString(m) }
func (*MUserInternalVerifyReq) ProtoMessage()               {}
func (*MUserInternalVerifyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MUserInternalVerifyReq) GetLID() int32 {
	if m != nil && m.LID != nil {
		return *m.LID
	}
	return 0
}

func (m *MUserInternalVerifyReq) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

func (m *MUserInternalVerifyReq) GetGID() int32 {
	if m != nil && m.GID != nil {
		return *m.GID
	}
	return 0
}

func (m *MUserInternalVerifyReq) GetConnCode() int32 {
	if m != nil && m.ConnCode != nil {
		return *m.ConnCode
	}
	return 0
}

type MUpdatePlayerRankReq struct {
	UID              *uint32 `protobuf:"varint,1,req,name=UID" json:"UID,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	Level            *uint32 `protobuf:"varint,3,req,name=Level" json:"Level,omitempty"`
	Job              *uint32 `protobuf:"varint,4,req,name=Job" json:"Job,omitempty"`
	Power            *uint32 `protobuf:"varint,5,req,name=Power" json:"Power,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MUpdatePlayerRankReq) Reset()                    { *m = MUpdatePlayerRankReq{} }
func (m *MUpdatePlayerRankReq) String() string            { return proto.CompactTextString(m) }
func (*MUpdatePlayerRankReq) ProtoMessage()               {}
func (*MUpdatePlayerRankReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MUpdatePlayerRankReq) GetUID() uint32 {
	if m != nil && m.UID != nil {
		return *m.UID
	}
	return 0
}

func (m *MUpdatePlayerRankReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MUpdatePlayerRankReq) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *MUpdatePlayerRankReq) GetJob() uint32 {
	if m != nil && m.Job != nil {
		return *m.Job
	}
	return 0
}

func (m *MUpdatePlayerRankReq) GetPower() uint32 {
	if m != nil && m.Power != nil {
		return *m.Power
	}
	return 0
}

type MCheckCanBuyOlshopItemReq struct {
	UID              *uint32 `protobuf:"varint,1,req,name=UID" json:"UID,omitempty"`
	GID              *uint32 `protobuf:"varint,2,req,name=GID" json:"GID,omitempty"`
	QueryId          *uint32 `protobuf:"varint,3,req,name=QueryId" json:"QueryId,omitempty"`
	Cost             *uint32 `protobuf:"varint,4,req,name=Cost" json:"Cost,omitempty"`
	ItemId           *uint32 `protobuf:"varint,5,req,name=ItemId" json:"ItemId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MCheckCanBuyOlshopItemReq) Reset()                    { *m = MCheckCanBuyOlshopItemReq{} }
func (m *MCheckCanBuyOlshopItemReq) String() string            { return proto.CompactTextString(m) }
func (*MCheckCanBuyOlshopItemReq) ProtoMessage()               {}
func (*MCheckCanBuyOlshopItemReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MCheckCanBuyOlshopItemReq) GetUID() uint32 {
	if m != nil && m.UID != nil {
		return *m.UID
	}
	return 0
}

func (m *MCheckCanBuyOlshopItemReq) GetGID() uint32 {
	if m != nil && m.GID != nil {
		return *m.GID
	}
	return 0
}

func (m *MCheckCanBuyOlshopItemReq) GetQueryId() uint32 {
	if m != nil && m.QueryId != nil {
		return *m.QueryId
	}
	return 0
}

func (m *MCheckCanBuyOlshopItemReq) GetCost() uint32 {
	if m != nil && m.Cost != nil {
		return *m.Cost
	}
	return 0
}

func (m *MCheckCanBuyOlshopItemReq) GetItemId() uint32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

type MCheckCanBuyOlshopItemRsp struct {
	Result           *int32  `protobuf:"varint,1,req,name=Result" json:"Result,omitempty"`
	UID              *uint32 `protobuf:"varint,2,req,name=UID" json:"UID,omitempty"`
	GID              *uint32 `protobuf:"varint,3,req,name=GID" json:"GID,omitempty"`
	QueryId          *uint32 `protobuf:"varint,4,req,name=QueryId" json:"QueryId,omitempty"`
	ItemId           *uint32 `protobuf:"varint,5,req,name=ItemId" json:"ItemId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MCheckCanBuyOlshopItemRsp) Reset()                    { *m = MCheckCanBuyOlshopItemRsp{} }
func (m *MCheckCanBuyOlshopItemRsp) String() string            { return proto.CompactTextString(m) }
func (*MCheckCanBuyOlshopItemRsp) ProtoMessage()               {}
func (*MCheckCanBuyOlshopItemRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MCheckCanBuyOlshopItemRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *MCheckCanBuyOlshopItemRsp) GetUID() uint32 {
	if m != nil && m.UID != nil {
		return *m.UID
	}
	return 0
}

func (m *MCheckCanBuyOlshopItemRsp) GetGID() uint32 {
	if m != nil && m.GID != nil {
		return *m.GID
	}
	return 0
}

func (m *MCheckCanBuyOlshopItemRsp) GetQueryId() uint32 {
	if m != nil && m.QueryId != nil {
		return *m.QueryId
	}
	return 0
}

func (m *MCheckCanBuyOlshopItemRsp) GetItemId() uint32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

type MSavePlayerExtDataReq struct {
	LID              *int32  `protobuf:"varint,1,req,name=LID" json:"LID,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	UID              *uint32 `protobuf:"varint,3,req,name=UID" json:"UID,omitempty"`
	ExtIndex         *uint32 `protobuf:"varint,4,req,name=ExtIndex" json:"ExtIndex,omitempty"`
	Data             []byte  `protobuf:"bytes,5,req,name=Data" json:"Data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MSavePlayerExtDataReq) Reset()                    { *m = MSavePlayerExtDataReq{} }
func (m *MSavePlayerExtDataReq) String() string            { return proto.CompactTextString(m) }
func (*MSavePlayerExtDataReq) ProtoMessage()               {}
func (*MSavePlayerExtDataReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MSavePlayerExtDataReq) GetLID() int32 {
	if m != nil && m.LID != nil {
		return *m.LID
	}
	return 0
}

func (m *MSavePlayerExtDataReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MSavePlayerExtDataReq) GetUID() uint32 {
	if m != nil && m.UID != nil {
		return *m.UID
	}
	return 0
}

func (m *MSavePlayerExtDataReq) GetExtIndex() uint32 {
	if m != nil && m.ExtIndex != nil {
		return *m.ExtIndex
	}
	return 0
}

func (m *MSavePlayerExtDataReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MLSAccessNtf struct {
	LID              *int32  `protobuf:"varint,1,req,name=LID" json:"LID,omitempty"`
	AccessToken      *string `protobuf:"bytes,2,req,name=AccessToken" json:"AccessToken,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MLSAccessNtf) Reset()                    { *m = MLSAccessNtf{} }
func (m *MLSAccessNtf) String() string            { return proto.CompactTextString(m) }
func (*MLSAccessNtf) ProtoMessage()               {}
func (*MLSAccessNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MLSAccessNtf) GetLID() int32 {
	if m != nil && m.LID != nil {
		return *m.LID
	}
	return 0
}

func (m *MLSAccessNtf) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

type MVerifyAccountReq struct {
	Account          *string `protobuf:"bytes,1,req,name=Account" json:"Account,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=Password" json:"Password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MVerifyAccountReq) Reset()                    { *m = MVerifyAccountReq{} }
func (m *MVerifyAccountReq) String() string            { return proto.CompactTextString(m) }
func (*MVerifyAccountReq) ProtoMessage()               {}
func (*MVerifyAccountReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MVerifyAccountReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *MVerifyAccountReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type MQuickMessageNtf struct {
	MsgId            *int32 `protobuf:"varint,1,req,name=MsgId" json:"MsgId,omitempty"`
	Param            *int32 `protobuf:"varint,2,req,name=Param" json:"Param,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MQuickMessageNtf) Reset()                    { *m = MQuickMessageNtf{} }
func (m *MQuickMessageNtf) String() string            { return proto.CompactTextString(m) }
func (*MQuickMessageNtf) ProtoMessage()               {}
func (*MQuickMessageNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MQuickMessageNtf) GetMsgId() int32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *MQuickMessageNtf) GetParam() int32 {
	if m != nil && m.Param != nil {
		return *m.Param
	}
	return 0
}

type MServerListItem struct {
	ServerName       *string `protobuf:"bytes,1,req,name=ServerName" json:"ServerName,omitempty"`
	ServerAddress    *string `protobuf:"bytes,2,req,name=ServerAddress" json:"ServerAddress,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MServerListItem) Reset()                    { *m = MServerListItem{} }
func (m *MServerListItem) String() string            { return proto.CompactTextString(m) }
func (*MServerListItem) ProtoMessage()               {}
func (*MServerListItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MServerListItem) GetServerName() string {
	if m != nil && m.ServerName != nil {
		return *m.ServerName
	}
	return ""
}

func (m *MServerListItem) GetServerAddress() string {
	if m != nil && m.ServerAddress != nil {
		return *m.ServerAddress
	}
	return ""
}

type MServerListNtf struct {
	Servers          []*MServerListItem `protobuf:"bytes,1,rep,name=Servers" json:"Servers,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *MServerListNtf) Reset()                    { *m = MServerListNtf{} }
func (m *MServerListNtf) String() string            { return proto.CompactTextString(m) }
func (*MServerListNtf) ProtoMessage()               {}
func (*MServerListNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *MServerListNtf) GetServers() []*MServerListItem {
	if m != nil {
		return m.Servers
	}
	return nil
}

type MVerifyAccountRsp struct {
	Result           *int32 `protobuf:"varint,1,req,name=Result" json:"Result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MVerifyAccountRsp) Reset()                    { *m = MVerifyAccountRsp{} }
func (m *MVerifyAccountRsp) String() string            { return proto.CompactTextString(m) }
func (*MVerifyAccountRsp) ProtoMessage()               {}
func (*MVerifyAccountRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MVerifyAccountRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*MRegisterServerReq)(nil), "protocol.MRegisterServerReq")
	proto.RegisterType((*MSavePlayerDataReq)(nil), "protocol.MSavePlayerDataReq")
	proto.RegisterType((*MUserInternalVerifyReq)(nil), "protocol.MUserInternalVerifyReq")
	proto.RegisterType((*MUpdatePlayerRankReq)(nil), "protocol.MUpdatePlayerRankReq")
	proto.RegisterType((*MCheckCanBuyOlshopItemReq)(nil), "protocol.MCheckCanBuyOlshopItemReq")
	proto.RegisterType((*MCheckCanBuyOlshopItemRsp)(nil), "protocol.MCheckCanBuyOlshopItemRsp")
	proto.RegisterType((*MSavePlayerExtDataReq)(nil), "protocol.MSavePlayerExtDataReq")
	proto.RegisterType((*MLSAccessNtf)(nil), "protocol.MLSAccessNtf")
	proto.RegisterType((*MVerifyAccountReq)(nil), "protocol.MVerifyAccountReq")
	proto.RegisterType((*MQuickMessageNtf)(nil), "protocol.MQuickMessageNtf")
	proto.RegisterType((*MServerListItem)(nil), "protocol.MServerListItem")
	proto.RegisterType((*MServerListNtf)(nil), "protocol.MServerListNtf")
	proto.RegisterType((*MVerifyAccountRsp)(nil), "protocol.MVerifyAccountRsp")
	proto.RegisterEnum("protocol.LSOp", LSOp_name, LSOp_value)
}

func init() { proto.RegisterFile("loginsvr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 597 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x15, 0x49, 0x43, 0xcb, 0xa4, 0x6e, 0xb7, 0xdb, 0x8b, 0x5c, 0x24, 0x24, 0x64, 0x5e, 0xaa,
	0x3e, 0x54, 0x15, 0x0f, 0x3c, 0x55, 0x42, 0x25, 0x45, 0x28, 0x28, 0xee, 0x25, 0xc1, 0x91, 0x90,
	0x90, 0xd0, 0x12, 0x4f, 0xd3, 0x28, 0xae, 0xd7, 0xec, 0x3a, 0x69, 0xf3, 0x55, 0xfc, 0x10, 0xb7,
	0xcf, 0xe0, 0x2e, 0x66, 0xed, 0x05, 0xd2, 0xd8, 0x05, 0xf1, 0x64, 0xcd, 0x8e, 0xe7, 0x9c, 0xb3,
	0x7b, 0xe6, 0xc0, 0x52, 0x24, 0xfb, 0x83, 0x58, 0x8f, 0xd5, 0x4e, 0xa2, 0x64, 0x2a, 0xf9, 0x42,
	0xf6, 0xe9, 0xc9, 0xc8, 0x7b, 0x08, 0xdc, 0x6f, 0x63, 0x7f, 0xa0, 0x53, 0x54, 0x1d, 0x54, 0x63,
	0x54, 0x6d, 0x7c, 0xcd, 0x39, 0x40, 0x5e, 0x1c, 0x8a, 0x73, 0x74, 0x6f, 0xdc, 0xad, 0x6c, 0xdd,
	0xe2, 0xeb, 0xe0, 0xe0, 0x65, 0x22, 0x35, 0xee, 0x87, 0xa1, 0x42, 0xad, 0xdd, 0x8a, 0x39, 0xf6,
	0x9e, 0x13, 0x40, 0x47, 0x8c, 0xf1, 0x38, 0x12, 0x13, 0x54, 0x07, 0x22, 0x15, 0x06, 0xa0, 0x0e,
	0xd5, 0x56, 0xf3, 0x20, 0x9b, 0xac, 0xf1, 0x45, 0x98, 0xcb, 0x70, 0xb2, 0x01, 0xd3, 0x0a, 0xa8,
	0x55, 0xa5, 0xc2, 0xe1, 0x0e, 0xd4, 0x5a, 0x38, 0xc6, 0xc8, 0x9d, 0xcb, 0x4a, 0xfa, 0xd3, 0x20,
	0xb8, 0x35, 0xaa, 0x16, 0x09, 0x7a, 0xc3, 0x0f, 0x34, 0xaa, 0x66, 0x4c, 0xe2, 0x62, 0x11, 0x75,
	0x51, 0x0d, 0x4e, 0x27, 0x05, 0xf8, 0x55, 0xa8, 0xef, 0xf7, 0x7a, 0xa4, 0xe8, 0x99, 0x1c, 0x62,
	0xfc, 0x87, 0xe5, 0x89, 0x65, 0xa9, 0x71, 0x06, 0x0b, 0x0d, 0x19, 0xc7, 0x0d, 0x19, 0x62, 0x46,
	0x54, 0xf3, 0x5e, 0xc0, 0x9a, 0x1f, 0x24, 0xa1, 0x48, 0xad, 0xee, 0xb6, 0x88, 0x87, 0x16, 0x38,
	0xb0, 0xc0, 0xce, 0x8c, 0xee, 0xdf, 0x52, 0x73, 0xe5, 0xf4, 0xe7, 0x53, 0xf9, 0xca, 0xea, 0xa6,
	0xde, 0xb1, 0xbc, 0x40, 0x95, 0x09, 0x77, 0xbc, 0x10, 0x36, 0xfd, 0xc6, 0x19, 0xf6, 0x86, 0x0d,
	0x11, 0x3f, 0x1a, 0x4d, 0x8e, 0x22, 0x7d, 0x26, 0x93, 0x66, 0x8a, 0xe7, 0x05, 0x0a, 0x2b, 0xb3,
	0x92, 0x15, 0xcb, 0x30, 0x7f, 0x32, 0x42, 0x35, 0x69, 0x86, 0x96, 0x83, 0x04, 0x34, 0xa4, 0x4e,
	0x2d, 0xc9, 0x12, 0xdc, 0x34, 0x18, 0xd4, 0xcd, 0x59, 0x4e, 0xaf, 0x65, 0xd1, 0x89, 0xf9, 0xb9,
	0x8d, 0x7a, 0x14, 0xa5, 0xf6, 0x91, 0x2c, 0x6b, 0x65, 0x9a, 0xb5, 0x3a, 0xcb, 0x5a, 0xce, 0xf3,
	0x12, 0xd6, 0xa7, 0x1c, 0x7e, 0x7c, 0x99, 0xfe, 0xaf, 0xc9, 0xf4, 0xfc, 0x34, 0xd5, 0x8c, 0x43,
	0xbc, 0x2c, 0xf5, 0x79, 0x17, 0x16, 0xfd, 0x56, 0x27, 0xf7, 0xf0, 0x30, 0x3d, 0xfd, 0xb7, 0xbb,
	0xde, 0x03, 0x58, 0xf1, 0xf3, 0x6d, 0xa0, 0x9e, 0x1c, 0xc5, 0xa9, 0x91, 0x43, 0x17, 0xb1, 0x95,
	0xdd, 0x58, 0xe2, 0x3d, 0x16, 0x5a, 0x5f, 0x48, 0x15, 0xda, 0xb9, 0x5d, 0x60, 0xfe, 0xc9, 0x68,
	0xd0, 0x1b, 0xfa, 0x04, 0x28, 0xfa, 0x68, 0xd8, 0xc8, 0x3b, 0x5f, 0xf7, 0xe9, 0xb6, 0x39, 0x9f,
	0xb1, 0x52, 0x28, 0x71, 0x9e, 0x4d, 0xd4, 0xbc, 0x3d, 0x58, 0xf6, 0xf3, 0x28, 0xb4, 0x28, 0x23,
	0xe6, 0x5d, 0xae, 0x0b, 0x47, 0x7e, 0x76, 0x35, 0x1c, 0x7b, 0xb0, 0x34, 0x35, 0x6d, 0xd8, 0xb6,
	0x61, 0x3e, 0x3f, 0xd0, 0x34, 0x59, 0xdd, 0xaa, 0xdf, 0xdf, 0xdc, 0xf9, 0x95, 0xc5, 0x9d, 0x19,
	0x22, 0xef, 0x5e, 0xe1, 0x96, 0x45, 0x63, 0xb7, 0xdf, 0x54, 0x60, 0xae, 0xd5, 0x39, 0x4a, 0xf8,
	0x06, 0xac, 0x14, 0x82, 0xcc, 0x3e, 0x05, 0xe6, 0xbc, 0x90, 0x4f, 0xf6, 0x39, 0xe0, 0xb7, 0x61,
	0xbd, 0x34, 0x5c, 0xec, 0x4b, 0xc0, 0x5d, 0x58, 0x2d, 0x49, 0x07, 0xfb, 0x1a, 0xf0, 0x3b, 0xe0,
	0x5e, 0xb7, 0xd9, 0xec, 0xdb, 0x5f, 0xda, 0x3a, 0x61, 0xdf, 0x03, 0xbe, 0x09, 0x6b, 0x65, 0x9b,
	0xc4, 0x7e, 0x04, 0x64, 0x56, 0x7d, 0x6a, 0x07, 0xd8, 0xdb, 0x2e, 0xbd, 0x29, 0x9b, 0xf5, 0x98,
	0xbd, 0xeb, 0xf2, 0x35, 0x58, 0x9e, 0xb1, 0x90, 0xbd, 0xef, 0x92, 0x29, 0xce, 0x95, 0x87, 0x66,
	0x1f, 0x4a, 0x00, 0x48, 0xc4, 0xc7, 0xee, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0x38, 0x3b,
	0xaf, 0x0d, 0x05, 0x00, 0x00,
}
